# -*- coding: utf-8 -*-
## This file is part of CDS Invenio.
## Copyright (C) 2002, 2003, 2004, 2005, 2006, 2007 CERN.
##
## CDS Invenio is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License as
## published by the Free Software Foundation; either version 2 of the
## License, or (at your option) any later version.
##
## CDS Invenio is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with CDS Invenio; if not, write to the Free Software Foundation, Inc.,
## 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

"""
Unoconv based WebSubmit File Converter.
"""

import os
import shutil
import time

from invenio.websubmit_file_converter_utils import execute_command, \
    InvenioWebSubmitFileConverterError, normalize_format
from invenio.config import CFG_OPENOFFICE_TMPDIR, CFG_OPENOFFICE_USER, \
    CFG_OPENOFFICE_SERVER_HOST, CFG_OPENOFFICE_SERVER_PORT, \
    CFG_PATH_OPENOFFICE_PYTHON

CFG_CONVERTER_NEEDS_WORKING_DIR = False

def check_prerequisities():
    """Return True if OpenOffice tmpdir do exists and OpenOffice can
    successfully create file there."""
    if not os.path.exists(CFG_OPENOFFICE_TMPDIR):
        raise InvenioWebSubmitFileConverterError('%s does not exists' % CFG_OPENOFFICE_TMPDIR)
    if not os.path.isdir(CFG_OPENOFFICE_TMPDIR):
        raise InvenioWebSubmitFileConverterError('%s is not a directory' % CFG_OPENOFFICE_TMPDIR)
    now = str(time.time())
    execute_command('sudo', '-u', CFG_OPENOFFICE_USER, CFG_PATH_OPENOFFICE_PYTHON, 'import os; open(os.path.join(%s, "test"), "w").write(%s)' % (repr(CFG_OPENOFFICE_TMPDIR), repr(now)))
    try:
        test = open(os.path.join(CFG_OPENOFFICE_TMPDIR, 'test')).read()
        if test != now:
            raise IOError
    except:
        raise InvenioWebSubmitFileConverterError("%s can't be properly written by OpenOffice.org or read by Apache" % CFG_OPENOFFICE_TMPDIR)

def converter(input_file, output_file, working_dir, output_format='text', **argd):
    """Use unconv to convert among OpenOffice understood documents."""
    from invenio.bibdocfile import normalize_format
    try:
        check_openoffice_tmpdir()
    except InvenioWebSubmitFileConverterError, err:
        register_exception(alert_admin=True, prefix='ERROR: it\'s impossible to properly execute OpenOffice.org conversions: %s' % err)
        raise

    try:
        tmpfile = tempfile.mktemp(dir=CFG_OPENOFFICE_TMPDIR, suffix=normalize_format(output_format))
        execute_command('sudo', '-u', CFG_OPENOFFICE_USER, CFG_PATH_OPENOFFICE_PYTHON, os.path.join(CFG_PYLIBDIR, 'invenio', 'unoconv.py'), '-v', '-s', CFG_OPENOFFICE_SERVER_HOST, '-p', CFG_OPENOFFICE_SERVER_PORT, '--outputfile', tmpfile, '-f', unoconv_format, input_file)
    except InvenioWebSubmitFileConverterError:
        time.sleep(5)
        execute_command('sudo', '-u', CFG_OPENOFFICE_USER, CFG_PATH_OPENOFFICE_PYTHON, os.path.join(CFG_PYLIBDIR, 'invenio', 'unoconv.py'), '-v', '-s', CFG_OPENOFFICE_SERVER_HOST, '-p', CFG_OPENOFFICE_SERVER_PORT, '--outputfile', tmpfile, '-f', unoconv_format, input_file)

    if not os.path.exists(tmpfile):
        raise InvenioWebSubmitFileConverterError('No output was generated by OpenOffice')

    output_format = normalize_format(output_format)

    execute_command('sudo', '-u', CFG_OPENOFFICE_USER, CFG_PATH_OPENOFFICE_PYTHON, '-c', 'import os; os.remove(%s)' % repr(tmpfile))
    return output_file

def get_conversion_map():
    ret = {}
    for iformat in ('.rtf', '.doc', '.odt', '.docx'):
        for oformat in ('.rtf', '.doc', '.odt', '.docx', '.txt', '.pdf;pdfa'):
            if oformat == iformat:
                continue
            if iformat not in ret:
                ret[iformat] = {}
            if oformat == '.txt':
                ret[iformat][oformat] = {'output_format' : 'text'}
            elif oformat == '.pdf;pdfa':
                ret[iformat][oformat] = {'output_format' : 'pdf'}
            else:
                ret[iformat][oformat] = {'output_format' : oformat[1:]}
    for iformat in ('.ppt', '.pps', '.odp', '.pptx'):
        for oformat in ('.ppt', '.pps', '.odp', '.pptx'. '.txt', '.pdf;pdfa'):
            if oformat == iformat:
                continue
            if iformat not in ret:
                ret[iformat] = {}
            if oformat == '.txt':
                ret[iformat][oformat] = {'output_format' : 'text'}
            elif oformat == '.pdf;pdfa':
                ret[iformat][oformat] = {'output_format' : 'pdf'}
            else:
                ret[iformat][oformat] = {'output_format' : oformat[1:]}
    for iformat in ('.xls', '.ods', '.xlsx'):
        for oformat in ('.xls', '.ods', '.xls', '.csv', '.pdf;pdfa'):
            if oformat == iformat:
                continue
            if iformat not in ret:
                ret[iformat] = {}
            elif oformat == '.pdf;pdfa':
                ret[iformat][oformat] = {'output_format' : 'pdf'}
            else:
                ret[iformat][oformat] = {'output_format' : oformat[1:]}
    return ret
