# -*- coding: utf-8 -*-
## This file is part of CDS Invenio.
## Copyright (C) 2002, 2003, 2004, 2005, 2006, 2007 CERN.
##
## CDS Invenio is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License as
## published by the Free Software Foundation; either version 2 of the
## License, or (at your option) any later version.
##
## CDS Invenio is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with CDS Invenio; if not, write to the Free Software Foundation, Inc.,
## 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

"""
OpenOffice.org wrapper (through unoconv)
"""

import os
import time
import tempfile

from invenio.bibdocfile import normalize_format
from invenio.websubmit_config import InvenioWebSubmitFileConverterError
from invenio.errorlib import register_exception
from invenio.config import CFG_OPENOFFICE_USER, CFG_OPENOFFICE_SERVER_HOST, CFG_OPENOFFICE_SERVER_PORT, CFG_PATH_OPENOFFICE_PYTHON, CFG_PYLIBDIR, CFG_TMPDIR
from invenio.shellutils import execute_command

CFG_OPENOFFICE_TMPDIR = os.path.join(CFG_TMPDIR, 'ooffice-tmp-files')

def converter(input_file, output_file):
    """Use unconv to convert among OpenOffice understood documents."""
    try:
        check_openoffice_tmpdir()
    except InvenioWebSubmitFileConverterError, err:
        register_exception(alert_admin=True, prefix='ERROR: it\'s impossible to properly execute OpenOffice.org conversions: %s' % err)
        raise

    if output_format == 'txt':
        unoconv_format = 'text'
    else:
        unoconv_format = output_format
    try:
        tmpfile = tempfile.mktemp(dir=CFG_OPENOFFICE_TMPDIR, suffix=normalize_format(output_format))
        execute_command('sudo', '-u', CFG_OPENOFFICE_USER, CFG_PATH_OPENOFFICE_PYTHON, os.path.join(CFG_PYLIBDIR, 'invenio', 'unoconv.py'), '-v', '-s', CFG_OPENOFFICE_SERVER_HOST, '-p', CFG_OPENOFFICE_SERVER_PORT, '--outputfile', tmpfile, '-f', unoconv_format, input_file)
    except InvenioWebSubmitFileConverterError:
        time.sleep(5)
        execute_command('sudo', '-u', CFG_OPENOFFICE_USER, CFG_PATH_OPENOFFICE_PYTHON, os.path.join(CFG_PYLIBDIR, 'invenio', 'unoconv.py'), '-v', '-s', CFG_OPENOFFICE_SERVER_HOST, '-p', CFG_OPENOFFICE_SERVER_PORT, '--outputfile', tmpfile, '-f', unoconv_format, input_file)

    if not os.path.exists(tmpfile):
        raise InvenioWebSubmitFileConverterError('No output was generated by OpenOffice')

    output_format = normalize_format(output_format)

    execute_command('sudo', '-u', CFG_OPENOFFICE_USER, CFG_PATH_OPENOFFICE_PYTHON, '-c', 'import os; os.remove(%s)' % repr(tmpfile))
    return output_file

def check_openoffice_tmpdir():
    """Return True if OpenOffice tmpdir do exists and OpenOffice can
    successfully create file there."""
    if not os.path.exists(CFG_OPENOFFICE_TMPDIR):
        raise InvenioWebSubmitFileConverterError('%s does not exists' % CFG_OPENOFFICE_TMPDIR)
    if not os.path.isdir(CFG_OPENOFFICE_TMPDIR):
        raise InvenioWebSubmitFileConverterError('%s is not a directory' % CFG_OPENOFFICE_TMPDIR)
    now = str(time.time())
    execute_command('sudo', '-u', CFG_OPENOFFICE_USER, CFG_PATH_OPENOFFICE_PYTHON, 'import os; open(os.path.join(%s, "test"), "w").write(%s)' % (repr(CFG_OPENOFFICE_TMPDIR), repr(now)))
    try:
        test = open(os.path.join(CFG_OPENOFFICE_TMPDIR, 'test')).read()
        if test != now:
            raise IOError
    except:
        raise InvenioWebSubmitFileConverterError("%s can't be properly written by OpenOffice.org or read by Apache" % CFG_OPENOFFICE_TMPDIR)

def check_prerequisites(input_format, output_format):
    check_openoffice_tmpdir()
    if not CFG_OPENOFFICE_USER:
        raise InvenioWebSubmitFileConverterError("CFG_OPENOFFICE_USER is not set")
    if not CFG_OPENOFFICE_SERVER_HOST:
        raise InvenioWebSubmitFileConverterError("CFG_OPENOFFICE_SERVER_HOST is not set")
    if not CFG_OPENOFFICE_SERVER_PORT:
        raise InvenioWebSubmitFileConverterError("CFG_OPENOFFICE_SERVER_PORT is not set")
    if not CFG_PATH_OPENOFFICE_PYTHON:
        raise InvenioWebSubmitFileConverterError("CFG_PATH_OPENOFFICE_PYTHON is not set")
